language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer install --prefer-dist --no-interaction

script:
  - phpunit --coverage-clover=cloverage.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover cloverage.xml
